### ISSUE TITLE
继续上一个问题

### ISSUE THREAD

**Issue by Chris317** [golddoushi/mcsolver#22]
刘老师，您好！ 最新版本实在是出不了数据，我将其换成了1.2.0版本，但又报错了

(base) [chris@node05 CrI3]$ python CrI3.py
unknown file or version (only support v1.2)
Traceback (most recent call last):
  File "/home/chris/mcsolver/CrI3/CrI3.py", line 3, in <module>
    mcsolver.loadMC("./CrI3With2NNCoupling")
  File "/home/chris/anaconda3/lib/python3.9/site-packages/mcsolver/__init__.py", line 9, in loadMC
    win.startSimulation(updateGUI=False,rpath=rpath)
  File "/home/chris/anaconda3/lib/python3.9/site-packages/mcsolver/win.py", line 40, in startSimulation
    TList=np.linspace(io.T0,io.T1,io.nT)
AttributeError: module 'fileio' has no attribute 'T0'

**Comment by golddoushi** [comment]
建议您最好还是使用最新版。把nthermal，nsweep，tau全部设置为1，nT也设置为1只计算1个温度点，使用1个核。跑一下试试看

**Comment by Chris317** [comment]
老师，我把nthermal，nsweep，tau全部设置为1，nT也设置为1只计算1个温度点，使用1个核，但是出现了以下错误

(base) [chris@node05 samples]$ python sim_XYmodel_under_Linux.py
loading dynamic library in /home/chris/anaconda3/lib/python3.9/site-packages/mcsolver-2.3.0-py3.9-linux-x86_64.egg/mcsolver/lib/_xylib.py
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/chris/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/chris/anaconda3/lib/python3.9/site-packages/mcsolver-2.3.0-py3.9-linux-x86_64.egg/mcsolver/win.py", line 35, in startMCForOn
    spin_i, spin_j, spin_ij, autoCorr, E, E2, U4=mcslave.mainLoopViaCLib_On(nsweep=nsweep,nthermal=nthermal,ninterval=ninterval,algo=algorithm,On=On)
  File "/home/chris/anaconda3/lib/python3.9/site-packages/mcsolver-2.3.0-py3.9-linux-x86_64.egg/mcsolver/mcMain.py", line 331, in mainLoopViaCLib_On
    mylib=CDLL(dll_path)
  File "/home/chris/anaconda3/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/chris/anaconda3/lib/python3.9/site-packages/mcsolver-2.3.0-py3.9-linux-x86_64.egg/mcsolver/lib/_xylib.py: invalid ELF header
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/mcsolver/ljj/mcsolver-master/samples/sim_XYmodel_under_Linux.py", line 3, in <module>
    mcsolver.loadMC("./Square_XY_isotropic")
  File "/home/chris/anaconda3/lib/python3.9/site-packages/mcsolver-2.3.0-py3.9-linux-x86_64.egg/mcsolver/__init__.py", line 17, in loadMC
    win.startSimulation(updateGUI=False,rpath=rpath)
  File "/home/chris/anaconda3/lib/python3.9/site-packages/mcsolver-2.3.0-py3.9-linux-x86_64.egg/mcsolver/win.py", line 131, in startSimulation
    for result in pool.imap_unordered(startMCForOn,paramPack_tmp):
  File "/home/chris/anaconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
OSError: /home/chris/anaconda3/lib/python3.9/site-packages/mcsolver-2.3.0-py3.9-linux-x86_64.egg/mcsolver/lib/_xylib.py: invalid ELF header
