### ISSUE TITLE
三维体系计算不了，好像有bug

### ISSUE THREAD

**Issue by Jiewang11** [golddoushi/mcsolver#44]
1 This is mcsolver's save file, version: 3.0
  2 Lattice:
  3 1.000000000 0.000000000 0.000000000
  4 0.500000000 0.866000000 0.000000000
  5 0.000000000 0.000000000 1.000000000
  6 Supercell used in MC simulations:
  7 8 8 8
  8 Orbitals in cell:
  9 8
 10 Positions, initial spin states and onsite-anisotropy of every orbital:
 11 orb 0: type 0 spin 1.500000000 pos [0.333333330 0.666666670 0.250000000] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 12 orb 1: type 0 spin 1.500000000 pos [0.666666670 0.333333330 0.750000000] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 13 orb 2: type 0 spin 1.500000000 pos [0.000000000 0.000000000 0.000000000] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 14 orb 3: type 0 spin 1.500000000 pos [0.000000000 0.000000000 0.500000000] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 15 orb 4: type 0 spin 1.500000000 pos [0.333333330 0.666666670 0.991459800] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 16 orb 5: type 0 spin 1.500000000 pos [0.333333330 0.666666670 0.508540200] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 17 orb 6: type 0 spin 1.500000000 pos [0.666666670 0.333333330 0.008540200] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 18 orb 7: type 0 spin 1.500000000 pos [0.666666670 0.333333330 0.491459800] Dx 0.000000000 Dy 0.000000000 Dz 0.000000000 h 0.000000000
 19 Bonds:
 20 10
 21 id, source, target, overLat, exchange matrix elements of each bond:
 22 bond 0: Jx -103.919270000 Jy -103.919270000 Jz -103.919270000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jz    y 0.000000000 orb 1 to orb 7 over [0 0 0]
 23 bond 1: Jx -103.919270000 Jy -103.919270000 Jz -103.919270000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jz    y 0.000000000 orb 0 to orb 5 over [0 0 0]
 24 bond 2: Jx 51.756550000 Jy 51.756550000 Jz 51.756550000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jzy 0.00    0000000 orb 3 to orb 5 over [0 0 0]
 25 bond 3: Jx 51.756550000 Jy 51.756550000 Jz 51.756550000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jzy 0.00    0000000 orb 3 to orb 7 over [0 0 0]
26 bond 4: Jx 51.756550000 Jy 51.756550000 Jz 51.756550000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jzy 0.00    0000000 orb 3 to orb 5 over [0 -1 0]
 27 bond 5: Jx 51.756550000 Jy 51.756550000 Jz 51.756550000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jzy 0.00    0000000 orb 3 to orb 7 over [-1 0 0]
 28 bond 6: Jx 51.756550000 Jy 51.756550000 Jz 51.756550000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jzy 0.00    0000000 orb 3 to orb 5 over [-1 -1 0]
 29 bond 7: Jx 51.756550000 Jy 51.756550000 Jz 51.756550000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jzy 0.00    0000000 orb 3 to orb 7 over [-1 -1 0]
 30 bond 8: Jx -103.919270000 Jy -103.919270000 Jz -103.919270000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jz    y 0.000000000 orb 0 to orb 4 over [0 0 -1]
 31 bond 9: Jx -103.919270000 Jy -103.919270000 Jz -103.919270000 Jxy 0.000000000 Jxz 0.000000000 Jyz 0.000000000 Jyx 0.000000000 Jzx 0.000000000 Jz    y 0.000000000 orb 1 to orb 6 over [0 0 1]
 32 Temperature scanning region:
 33 Tmin 10.000000000 Tmax 400.000000000 nT 39
 34 Field scanning region (in unit 1.48872 T, only if Kelvin and uB is used for energy and spin):
 35 Hmin 0.000000000 Hmax 0.100000000 nH 1
 36 Dipole long-range coupling:
 37 alpha 0.000000
 38 Measurement:
 39 measure the correlation function between orb0 and orb0 over [0 0 0]
 40 OrbGroup:1
 41 Supergroup
 42 group0 orb0-orb0
 43 >>>       Topological section      <<<
 44 LocalCircuit per cell: 0 (set to 0 to skip the calc. for topo. Q)
 45 >>>   End of Topological section   <<<
 46 Distribution output frame: 0
 47 Sweeps for thermalization and statistics, and relaxiation step for each sweep:
48 40000 80000 0
 49 XAxis type:
 50 T
 51 Model type:
 52 Heisenberg
 53 Algorithm:
 54 Metropolis
 55 Ncores:
 56 96
=================================================================
这是输入文件，启动后，结果输出
-----------------------------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/jw/Documents/yes/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/jw/Documents/yes/lib/python3.11/site-packages/mcsolver-3.0.6-py3.11-linux-x86_64.egg/mcsolver/win.py", line 34, in startMCForOn
    mcslave=mc.MC(ID,LMatrix,pos=pos,S=S,D=DList,bondList=bondList,T=T,Lx=Lx,Ly=Ly,Lz=Lz,ki_s=GcOrb[0][0],ki_t=GcOrb[0][1],ki_overLat=GcOrb[1],orbGroupList=orbGroupList,groupInSC=groupInSC,h=h,dipoleAlpha=dipoleAlpha,On=On,spinFrame=spinFrame,localCircuitList=localCircuit)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jw/Documents/yes/lib/python3.11/site-packages/mcsolver-3.0.6-py3.11-linux-x86_64.egg/mcsolver/mcMain.py", line 37, in __init__
    lat.constructLocalFrame(self.lattice)
  File "/home/jw/Documents/yes/lib/python3.11/site-packages/mcsolver-3.0.6-py3.11-linux-x86_64.egg/mcsolver/Lattice.py", line 294, in constructLocalFrame
    orb.invFactorMat=np.linalg.inv(improveTheMatrixRankToThree(factorMatrix))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jw/Documents/yes/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 555, in inv
    _assert_stacked_2d(a)
  File "/home/jw/Documents/yes/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 206, in _assert_stacked_2d
    raise LinAlgError('%d-dimensional array given. Array must be '
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mcsolver-master/samples/mc.py", line 3, in <module>
    mcsolver.loadMC("./cr2te3")
  File "/home/jw/Documents/yes/lib/python3.11/site-packages/mcsolver-3.0.6-py3.11-linux-x86_64.egg/mcsolver/__init__.py", line 17, in loadMC
    win.startSimulation(updateGUI=False,rpath=rpath)
  File "/home/jw/Documents/yes/lib/python3.11/site-packages/mcsolver-3.0.6-py3.11-linux-x86_64.egg/mcsolver/win.py", line 132, in startSimulation
    for result in pool.imap_unordered(startMCForOn,paramPack_tmp):
  File "/home/jw/Documents/yes/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
numpy.linalg.LinAlgError: 0-dimensional array given. Array must be at least two-dimensional
============================================================================
刘博能不能看看时什么原因导致的

**Comment by wfx939** [comment]
请问一下您解决这个问题了吗？
