### ISSUE TITLE
XY模型计算报错

### ISSUE THREAD

**Issue by IMPLICIT-NONE** [golddoushi/mcsolver#6]
您好，在尝试使用您的软件计算 XY 模型的磁有序温度。下载了最新的安装包，使用 samples 中的 Square_XY_isotropic 进行测试，使用 4 核心计算时，输出正常，但是将核心数增大到 8 以后，计算报错。错误信息如下：

================
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
loading dynamic library in /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/public/home/Pwudx/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/win.py", line 28, in startMCForOn
    spin_i, spin_j, spin_ij, autoCorr, E, E2, U4=mcslave.mainLoopViaCLib_On(nsweep=nsweep,nthermal=nthermal,ninterval=ninterval,algo=algorithm,On=On)
  File "/public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/mcMain.py", line 326, in mainLoopViaCLib_On
    mylib=CDLL(dll_path)
  File "/public/home/Pwudx/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so: cannot map zero-fill pages: Cannot allocate memory
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sim_XYmodel_under_Linux.py", line 3, in <module>
    mcsolver.loadMC("./Square_XY_isotropic")
  File "/public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/__init__.py", line 9, in loadMC
    win.startSimulation(updateGUI=False,rpath=rpath)
  File "/public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/win.py", line 124, in startSimulation
    for result in pool.imap_unordered(startMCForOn,paramPack_tmp):
  File "/public/home/Pwudx/anaconda3/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
OSError: /public/home/Pwudx/anaconda3/lib/python3.6/site-packages/mcsolver/xylib.so: cannot map zero-fill pages: Cannot allocate memory
=========================

其他信息：
1. 为了提高测试速度，将超胞大小降为了 16  16  1，thermalization 和 relaxiation 步数降为了 40000 和 80000。
2. 用了 anoconda3 部署环境

感谢您的耐心回复。

**Comment by Nick12-hub** [comment]
It is obvious that your machine does not have enough memory to support it.
